// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_stream.proto

package com.hry.spring.grpc.mystream;

public interface SimpleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Simple)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num = 1;</code>
   */
  int getNum();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
