// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_stream.proto

package com.hry.spring.grpc.mystream;

public interface SimpleFeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleFeature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Simple location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.Simple location = 2;</code>
   */
  Simple getLocation();
  /**
   * <code>.Simple location = 2;</code>
   */
  SimpleOrBuilder getLocationOrBuilder();
}
